namespace Galaxy.Api
{
	
	public enum GogServicesConnectionState
	{
		GOG_SERVICES_CONNECTION_STATE_UNDEFINED,
		GOG_SERVICES_CONNECTION_STATE_CONNECTED,
		GOG_SERVICES_CONNECTION_STATE_DISCONNECTED,
		GOG_SERVICES_CONNECTION_STATE_AUTH_LOST
	}
}