namespace Galaxy.Api
{
	
	public enum LeaderboardDisplayType
	{
		LEADERBOARD_DISPLAY_TYPE_NONE,
		LEADERBOARD_DISPLAY_TYPE_NUMBER,
		LEADERBOARD_DISPLAY_TYPE_TIME_SECONDS,
		LEADERBOARD_DISPLAY_TYPE_TIME_MILLISECONDS
	}
}