namespace Galaxy.Api
{
	
	public enum LobbyComparisonType
	{
		LOBBY_COMPARISON_TYPE_EQUAL,
		LOBBY_COMPARISON_TYPE_NOT_EQUAL,
		LOBBY_COMPARISON_TYPE_GREATER,
		LOBBY_COMPARISON_TYPE_GREATER_OR_EQUAL,
		LOBBY_COMPARISON_TYPE_LOWER,
		LOBBY_COMPARISON_TYPE_LOWER_OR_EQUAL
	}
}