namespace Galaxy.Api
{
	
	public enum LobbyEnterResult
	{
		LOBBY_ENTER_RESULT_SUCCESS,
		LOBBY_ENTER_RESULT_LOBBY_DOES_NOT_EXIST,
		LOBBY_ENTER_RESULT_LOBBY_IS_FULL,
		LOBBY_ENTER_RESULT_ERROR,
		LOBBY_ENTER_RESULT_CONNECTION_FAILURE
	}
}