namespace Galaxy.Api
{
	
	public enum LobbyTopologyType
	{
		DEPRECATED_LOBBY_TOPOLOGY_TYPE_FCM_HOST_MIGRATION,
		LOBBY_TOPOLOGY_TYPE_FCM,
		LOBBY_TOPOLOGY_TYPE_STAR,
		LOBBY_TOPOLOGY_TYPE_CONNECTIONLESS,
		LOBBY_TOPOLOGY_TYPE_FCM_OWNERSHIP_TRANSITION
	}
}