namespace Galaxy.Api
{
	
	public enum OverlayState
	{
		OVERLAY_STATE_UNDEFINED,
		OVERLAY_STATE_NOT_SUPPORTED,
		OVERLAY_STATE_DISABLED,
		OVERLAY_STATE_FAILED_TO_INITIALIZE,
		OVERLAY_STATE_INITIALIZED
	}
}