namespace GlobalEnums
{
	
	public enum MainMenuState
	{
		LOGO,
		MAIN_MENU,
		OPTIONS_MENU,
		GAMEPAD_MENU,
		KEYBOARD_MENU,
		SAVE_PROFILES,
		AUDIO_MENU,
		VIDEO_MENU,
		EXIT_PROMPT,
		OVERSCAN_MENU,
		GAME_OPTIONS_MENU,
		ACHIEVEMENTS_MENU,
		QUIT_GAME_PROMPT,
		RESOLUTION_PROMPT,
		BRIGHTNESS_MENU,
		PAUSE_MENU,
		PLAY_MODE_MENU,
		EXTRAS_MENU,
		REMAP_GAMEPAD_MENU,
		EXTRAS_CONTENT_MENU,
		ENGAGE_MENU,
		NO_SAVE_MENU,
		DYNAMIC_MENU
	}
}